// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthLogout() {
  return window['go']['main']['App']['AuthLogout']();
}

export function AuthStartLogin() {
  return window['go']['main']['App']['AuthStartLogin']();
}

export function AuthStatus() {
  return window['go']['main']['App']['AuthStatus']();
}

export function DirHome() {
  return window['go']['main']['App']['DirHome']();
}

export function DirList(arg1) {
  return window['go']['main']['App']['DirList'](arg1);
}

export function SessionAddCommand(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SessionAddCommand'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SessionCreate(arg1, arg2, arg3) {
  return window['go']['main']['App']['SessionCreate'](arg1, arg2, arg3);
}

export function SessionDelete(arg1) {
  return window['go']['main']['App']['SessionDelete'](arg1);
}

export function SessionGet(arg1) {
  return window['go']['main']['App']['SessionGet'](arg1);
}

export function SessionList() {
  return window['go']['main']['App']['SessionList']();
}

export function SessionRename(arg1, arg2) {
  return window['go']['main']['App']['SessionRename'](arg1, arg2);
}

export function TerminalAvailableShells() {
  return window['go']['main']['App']['TerminalAvailableShells']();
}

export function TerminalClose(arg1) {
  return window['go']['main']['App']['TerminalClose'](arg1);
}

export function TerminalCreate(arg1, arg2) {
  return window['go']['main']['App']['TerminalCreate'](arg1, arg2);
}

export function TerminalResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['TerminalResize'](arg1, arg2, arg3);
}

export function TerminalWrite(arg1, arg2) {
  return window['go']['main']['App']['TerminalWrite'](arg1, arg2);
}
