// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {directory} from '../models';

export function AuthLogout():Promise<void>;

export function AuthStartLogin():Promise<void>;

export function AuthStatus():Promise<main.AppStatusDTO>;

export function DirHome():Promise<string>;

export function DirList(arg1:string):Promise<Array<directory.Entry>>;

export function SessionAddCommand(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<void>;

export function SessionCreate(arg1:string,arg2:string,arg3:string):Promise<main.SessionDTO>;

export function SessionDelete(arg1:string):Promise<void>;

export function SessionGet(arg1:string):Promise<main.SessionDTO>;

export function SessionList():Promise<Array<main.SessionDTO>>;

export function SessionRename(arg1:string,arg2:string):Promise<void>;

export function SessionTouch(arg1:string):Promise<void>;

export function SessionUpdateDir(arg1:string,arg2:string):Promise<void>;

export function TerminalAvailableShells():Promise<Array<string>>;

export function TerminalClose(arg1:string):Promise<void>;

export function TerminalCreate(arg1:string,arg2:string):Promise<string>;

export function TerminalInjectHistory(arg1:string,arg2:string):Promise<void>;

export function TerminalResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function TerminalWrite(arg1:string,arg2:string):Promise<void>;
